### ISSUE TITLE
08/07/20: VWS/Covid19NotificationApp - Can't enable notification exposure api on iOS 14 beta

### ISSUE THREAD

**Issue by milo526** [minvws/nl-covid19-notification-app-ios#15]
### Describe the bug, issue or concern

App doesn't work with iOS 14

### To Reproduce
1. Following on-boarding
2. On the screen where you can enable the exposure notification API, press "Aanzetten"

OR

1. Follow previous reproduce steps
2. Press "Sla over" on the screen with the "Aanzetten" button
3. Finish onboarding
4. Press "Instellingen aanzetten"

### Expected behaviour
The ability to enable the Exposure Notification API

### Screenshots
<img src="https://user-images.githubusercontent.com/5261909/86907009-b0ec3c00-c114-11ea-8d57-2eedf636bb7a.jpeg" width="414px" />

<img src="https://user-images.githubusercontent.com/5261909/86907037-bb0e3a80-c114-11ea-9302-20220c7a28cb.jpeg" width="414px" />

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 14.0 (18A5301v)
 - Browser: irrelevant
 - Version: App version v0.1 (256)

### Additional context
I'm running the iOS developer beta, seemingly the [ExposureNotifcation API](https://developer.apple.com/documentation/exposurenotification) is not enabled for these iOS builds source: [iOS & iPadOS 14 Beta 2 Release Notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by milo526** [comment]
Extra "problem" here; If I finalise the onboarding and get to the screen in the second screenshot; I can force-close the app after which it forces me to go through the onboarding again.
This behaviour is not reproduced on my other iPhone that has the ExposureNotificationAPI enabled. This other iPhone skips onboarding after I finalised it the first time (even if I disable the API in settings)

**Comment by TizianoCoroneo** [comment]
It is mentioned in the [iOS 14 release notes](
https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes) that the ExposureNotification framework won't work. 
You can test with iOS 13.6 beta 3

**Comment by rvandijke** [comment]
We will verify iOS 14 soon, I'll keep this issue open for now.

**Comment by bre7** [comment]
Exposure Notifications support added in iOS 14 Dev Beta 4 👏 

![ios14](https://user-images.githubusercontent.com/3183848/89342496-3feb6600-d679-11ea-8250-5c42aae77b8f.png)

**Comment by jesse-deboer** [comment]
Worked on iOS 14 Beta 4, but is not working anymore on beta 5!

**Comment by milo526** [comment]
Same as @jesse-deboer here!

Until I set the active region I saw the following: ![image](https://user-images.githubusercontent.com/5261909/90671490-16bffd80-e255-11ea-807d-8031f9f2ee00.jpeg)

**Comment by roelspruit** [comment]
I'm going to close this ticket. The original problem seemed related to beta builds of iOS. We are already aware of the fact that in some situations the "region" is not selected and the user has to perform a manual action to enable it again. We have a ticket to fix this and also an issue here that relates to that.
