### ISSUE TITLE
08/07/20: VWS/Covid19NotificationApp - Missing text replacement

### ISSUE THREAD

**Issue by milo526** [minvws/nl-covid19-notification-app-ios#16]
### Describe the bug, issue or concern

The app name is so secretive that even the app itself cannot know what name it is, if your iOS version is too low (lower than 13.5) you get a screen information you that "[Naam app] heeft iOS 13.5 of hoger nodig ...."

### To Reproduce
1. Open app on incompatible iOS version

### Expected behavior
A proper string placed in the place of "[Naam app]"

### Screenshots
<img src="https://user-images.githubusercontent.com/5261909/86909317-31f90280-c118-11ea-9a34-ef24e1716c41.jpeg" width="414px" />

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13.2 (17B84)
 - Version: App Version 0.1 (256)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by rvandijke** [comment]
This has been addressed, thanks for reporting
