### ISSUE TITLE
Reproducible build for iOS app

### ISSUE THREAD

**Issue by jsoeterbroek** [minvws/nl-covid19-notification-app-ios#23]
On https://github.com/minvws/nl-covid19-notification-app-coordination/issues/6 there is a discussion on how to allow for reproducable builds. This issue is to implement a possible solution for iOS app.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by jsoeterbroek** [comment]
A possible solution could be to use the solution that is written up at https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios. I have implemented this solution with a modified python script to compare binaries.

**The big (remaining) issue is that it requires a jailbroken device equipped with tools for decrypting apps (step 9).** 

I am using a CI build step in Github Actions to compare the build ipa binary with a known good (test-)file and a known 'evil' (test-)ipa file. 

Patch is available at 
https://github.com/jsoeterbroek/nl-covid19-notification-app-ios/tree/patch-ipadiff

I would welcome any suggestions and improvements.

**Comment by jsoeterbroek** [comment]
example output:

```
***************************************
* ipadiff good versus good...
*  - ARTIFACT_FROM_BUILD_IPA path/to/artifact/build/artifact.ipa
*  - FILE_FROM_APPSTORE_IPA_GOOD path/to/artifact/appstore/test-good.ipa
***************************************

IPAs are equal
    IPAs contain .nib (compiled Interface Builder) files that are compiled by the App Store and can't currently be checked:
        Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
        Base.lproj/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib
        Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
        Base.lproj/Main.storyboardc/UIViewController-BYZ-38-t0r.nib

***************************************
* ipadiff good versus evil...
*  - ARTIFACT_FROM_BUILD_IPA path/to/artifact/build/artifact.ipa
*  - FILE_FROM_APPSTORE_IPA_GOOD path/to/artifact/appstore/test-evil.ipa
***************************************

Files not present in path/to/artifact/build/artifact.ipa
    PlugIns/calculatorTests.xctest/Frameworks/libswiftDarwinEvil.dylib
IPAs are not equal
##[error]Process completed with exit code 1.
```

**Comment by roelspruit** [comment]
I'm sorry this has been left open and without comment for such a long time. We have had quite some work to do over the last year and this issue never got enough priority over functional work, even though it would have been nice to have ticked this box. 

In the original discussion on https://github.com/minvws/nl-covid19-notification-app-coordination/issues/6 It was decided that the Escrow approach that was taken for release build validation was sufficient. Additionally, it seems the open source code that was used in the PR for this (https://github.com/minvws/nl-covid19-notification-app-ios/pull/24) still does not have a clear license attached to it. That makes it impractical to continue with this approach.

For this reason, I'm going to close this issue and the PR associated with it. I do want to thank you for the work you put into this and once again I'm sorry we couldn't make better use of it.
