### ISSUE TITLE
Onvertaalde tekst rondom "Hoe verwijder ik bluetoothgegevens"

### ISSUE THREAD

**Issue by HenkPoley** [minvws/nl-covid19-notification-app-ios#29]
In test- en onderzoeksversie 1.0.2 

Er ontbreekt moreInformation.about.faq.deletion.description

Hier: https://github.com/minvws/nl-covid19-notification-app-ios/blob/86b1502dcbb42c76040610bea4c5b8ca55bf953b/Sources/ENCore/Resources/nl.lproj/Localizable.strings#L250

![C97A225F-EA59-455F-B4AE-F705ABE7B350](https://user-images.githubusercontent.com/2931213/90378338-85486400-e079-11ea-83ec-d7618e2ffab6.png)

**Comment by sbarow** [comment]
This should be fixed now.

**Comment by HenkPoley** [comment]
Cool, you can close this one I guess: https://github.com/minvws/nl-covid19-notification-app-ios/pull/30
