### ISSUE TITLE
2020-08-18: [VWS/Covid19NotificationApp] Rate this app does not work

### ISSUE THREAD

**Issue by donkersgoed** [minvws/nl-covid19-notification-app-ios#35]
### Describe the bug, issue or concern

Pressing the 'Rate the app' button does not do anything.

### To Reproduce
1. Go to 'About this app'
2. Click on 'Rate the app'
3. Nothing happens.

### Expected behavior
A rating popup, I guess?

### Screenshots
![5232E5D6-27F7-4953-A581-1CBDB4B74285](https://user-images.githubusercontent.com/4188922/90552115-a2248a80-e192-11ea-89af-207e9c348a7f.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.6
 - Browser: N/A
 - Version: 1.0.3

### Additional context
N/A

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by sbarow** [comment]
Thanks for the report @donkersgoed it looks like this is an issue when you have already submitted a rating and then try rate the app again.

**Comment by donkersgoed** [comment]
I haven't been able to rate even once though..

**Comment by Arjanvanmaren** [comment]
I had this exact behavior after submitting my review for in the Appstore. The first time it worked as expected and I could send the review but the next time the button doesn’t do anything.

**Comment by sbarow** [comment]
This should be fixed now in v1.0.5

**Comment by donkersgoed** [comment]
Confirmed, works now. Closing issue.
