### ISSUE TITLE
[2020-08-21]: [VWS/Covid19NotificationApp] iOS multiple exposure checks at same time

### ISSUE THREAD

**Issue by TeunVR** [minvws/nl-covid19-notification-app-ios#39]
### Describe the bug, issue or concern

When the app is launched manually sometimes multiple exposure checks are added to the list at the same time.

### To Reproduce

Launch the app.
Go to settings privacy health covid settings and look at exposure checks list. Sometimes there are multiple checks at the same time.

### Expected behavior
Only one check at each time?

### Screenshots
iPhone SE1 at iOS 13.6 and iPhone SE2 at iOS 13.6.1
![FF28FB91-B232-4A7F-BBDB-782DE5941DCD](https://user-images.githubusercontent.com/69744/90929879-e1084980-e3f9-11ea-8d1e-af837958bdc1.jpeg)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by rvandijke** [comment]
We are feeding multiple exposure keysets to the API at the same time (see https://github.com/minvws/nl-covid19-notification-app-ios/blob/edc489b614da4149cfe68d629826aeb2fe06702c/Sources/ENCore/App/Features/ExposureController/ExposureData/OperationProvider/Operations/ProcessExposureKeySetsDataOperation.swift#L184)

I'm assuming iOS will make a new entry for every file processed, but I'll validate this in the next days.

**Comment by roelspruit** [comment]
@rvandijke did you do this check back in august? I'm trying to update the status of open issues and PRs currently so I would like to know the status of this.

**Comment by roelspruit** [comment]
I'm closing this issue. This doesn't seem to happen anymore.
