### ISSUE TITLE
Volledige implementatie van huidige figma design

### ISSUE THREAD

**Issue by AndreasVerhoeven** [minvws/nl-covid19-notification-app-ios#4]
Mij was gevraagd om deel te nemen aan dit project als iOS developer, maar wegens tijdgebrek (en andere redenen) heb ik dat niet gedaan.

Heb wel een paar dagen geleden snel het huidige (0.4) Figma design vertaald naar een iOS app: https://github.com/AndreasVerhoeven/CovidAppDesign

Features:
 - Volledig support voor VoiceOver
 - Volledig support voor Dynamic Type
 - Volledig support voor alle iPhones en iPads
 - Volledig scalable (text overflowed scrollable wanneer deze niet past) 
 - Dark mode support
 - Accessibility"Smart invert" support
 - Accessibility "Reduced motion"  support
 - Switch control support
 - Geen gebruik van deprecated iOS APIs (bijv. navigation bar API)
 - Correcte manier van buttons highlighten
 - Geen 3rd party libs
 - Geen layout code  in ViewControllers, maar in Views :)

**Comment by tom-wolters** [comment]
Sounds good! I'm not an legal expert, but all your header files include a copyright to you. Is that not an issue to use your code(?).

**Comment by arianvp** [comment]
The code would indeed have to have a LICENSE that allows you to copy it and is compatible with the EUPL license. in the current state you wouldn't be able to use it

**Comment by rvandijke** [comment]
Given the changes in architecture and design I will close this for now.
