### ISSUE TITLE
[DATE]: [VWS/Covid19NotificationApp] Active app flashes ‘app is not active’ screen

### ISSUE THREAD

**Issue by jurb** [minvws/nl-covid19-notification-app-ios#41]
### Describe the bug, issue or concern

When opening the app after a few hours, I get a brief flash of a screen indicating the app is not active (it goes by so fast I can’t make a screen shot or read everything). After that it correctly shows the ‘app is active’ screen.

### To Reproduce

1. Open the app without it being in active memory, say after an hour
2. See the error

### Expected behavior

A blank or loading screen until the active status has been polled.

### OS

latest iOS 13

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by rvandijke** [comment]
Hi @jurb, thanks for reporting this. This issue should be fixed by https://github.com/minvws/nl-covid19-notification-app-ios/commit/739006262ee3cc4587d80c21811a73164db12e15. Could you please validate this again in the next AppStore build (most likely v 1.0.5 or 1.1) once it's available? We hope to release a new version somewhere this week.

**Comment by jurb** [comment]
> Hi @jurb, thanks for reporting this. This issue should be fixed by [7390062](https://github.com/minvws/nl-covid19-notification-app-ios/commit/739006262ee3cc4587d80c21811a73164db12e15). Could you please validate this again in the next AppStore build (most likely v 1.0.5 or 1.1) once it's available? We hope to release a new version somewhere this week.

Yep, not reproducible on 1.0.5!
