### ISSUE TITLE
[25-08-2020]: [VWS/Covid19NotificationApp] Disable links when having no internet available

### ISSUE THREAD

**Issue by Arjanvanmaren** [minvws/nl-covid19-notification-app-ios#42]
### Describe the bug, issue or concern

When internet is disabled, users can still navigate to the accessibility and the colofon page. But the action results in a blank page.

### To Reproduce
1. Disable all wifi and cellular services on device
2. Go to about the app
3. Click on colofon or accessibility 
4. See blank page

### Screenshots
![534C8711-57DD-4078-869D-24B24E592F63](https://user-images.githubusercontent.com/16067826/91212698-dfe45e80-e710-11ea-86d6-3cd54b792569.png)

### Expected behavior
I would expect a warning message to appear or the links to be disabled when flight mode is on.

**Smartphone (please complete the following information):**
 - Device: iPhone11 Pro
 - OS: iOS 13.6.1
 - Browser stock browser, safari
 - Version 1.0.4

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
Thank you for reporting this. Just for your information, we have created an internal ticket to fix this issue (ticket nr. 58909)

**Comment by roelspruit** [comment]
We just released version 1.1 of the app with a fix for this issue. Again, thanks for your report. I'm going to close this issue now.
