### ISSUE TITLE
iOS 13.7-14.0.1 bug? App suddenly inactive.

### ISSUE THREAD

**Issue by HenkPoley** [minvws/nl-covid19-notification-app-ios#44]
### Describe the bug, issue or concern

Without user intervention the app displays (after 24 hours?):

"App is niet actief" (status.appState.card.title)
"CoronaMelder werkt alleen als de noodzakelijke instellingen aanstaan." (status.appState.card.description)

The app directs you to iOS Settings, where there is _no_ toggle to turn it _even more_ 'on'. Though settings does show CoronaMelder as 'inactive' ('inactief').

In the App Store 'CoronaMelder' is shown as installed 'yesterday'. Which could possibly have caused this problem to show up after 24 hours.

Bluetooth is on.

iPhone 11 is rebooted.

Never chose to disable the tracking.

Issue did not resolve itself.

### To Reproduce

?

### Expected behavior
App / Apple API should stay active.

### Screenshots

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS13.7

### Governance
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by HenkPoley** [comment]
Upgrade to iOS 14 resolved this 🤷‍♂️

**Comment by Nikooos** [comment]
I currently have the same problem on iOS 14.0.1.

I had the app installed some weeks before and then it was working.

I will try a reboot now and let you know if this fixes it.

**Comment by Rknegt** [comment]
> I currently have the same problem on iOS 14.0.1.
> 
> 
> 
> I had the app installed some weeks before and then it was working.
> 
> 
> 
> I will try a reboot now and let you know if this fixes it.
> 
> 
> 
> Update: A reboot is not fixing it for me. 

Device info: Iphone XR IOS 14.0.1 
App version: 1.0.9

I also have this problem. I have disabled the exposure tracking for 2 weeks and I wanted to turn it on again before the local launch but the exposure notifications screen is blank. But when I install the german warn app, I also can't enable that app. So it looks like it's not the app's problem but maybe more of the API or my device?

# What I have tried to fix the issue:
- Multiple reboots and reinstalling the app multiple times

![Exposure notifications IOS settings](https://user-images.githubusercontent.com/51092169/95423937-2baa3a80-0942-11eb-9617-dfc88bea652e.png)

![Exposure notification screen is blank](https://user-images.githubusercontent.com/51092169/95423955-306eee80-0942-11eb-8751-20d6592c4b36.png)

**Comment by roelspruit** [comment]
Hi. The team has a fix for this blank screen in the upcoming version that will be released in the upcoming days.

**Comment by Nikooos** [comment]
A quick update on my side. I haven't checked the app since my last reply here. It now shows as active again.
Didn't change anything myself on this.

**Comment by Rknegt** [comment]
Update: I have updated to the latest version of the app (1.0.10) but it did not fix my problem. However, I saw [somewhere](https://faq.covid19.nhs.uk/article/KA-01303/en-us?parentid=CAT-01029&rootid=CAT-01024) that resetting your location and privacy settings could fix the problem. And after the reset of my privacy and location settings I did a reboot and reinstalled the app and it now works.

**Comment by roelspruit** [comment]
Thank you for checking this and letting us know. This seems like a similar issue as reported [here](https://github.com/minvws/nl-covid19-notification-app-ios/issues/52). I'm going to close this ticket so we can keep the discussion in a single place.
