### ISSUE TITLE
Unable to Re-enable after Location & Privacy Reset

### ISSUE THREAD

**Issue by johankool** [minvws/nl-covid19-notification-app-ios#45]
### Describe the bug, issue or concern

It is possible to get the app in a state where it is disabled and cannot be enabled again.

First reported on Code for NL Slack [here](https://codefornl.slack.com/archives/C014UMBE890/p1600409820006800).

### To Reproduce
1. Have the CoronaMelder app installed and active
1. Go to iOS Settings
2. Click on General > Reset
3. Click "Reset Location & Privacy" and complete reset
4. Open CoronaMelder and notice it is now disabled
5. Follow steps to re-enable
6. The screen to re-enable Exposure notifications in iOS settings is blank

### Expected behavior
Of course I should be able to enable the app again.

### Workaround
Hard kill of the app and restart of the device and disable Exposure notifications doesn't help. Deleting the app and reinstalling it allows for the app to go through the normal onboarding flow again and the app can be enabled again properly.

### Analysis
My interpretation of this issue is that by resetting the privacy settings the app gets into the state where it can walk through the onboarding flow again, but the app thinks it already has done this and so sends the user to Exposure Notification screen in Settings. But Apple made it so that this can only be enabled from the app.

It seems that the app keeps track of wether the user has gone through the onboarding and decides based on that what it does on subsequent launches and also assumes that in the main screen that when it is disabled the user always must go to the Settings. Instead it probably should look at the status of the framework to see if user already gave permission or not. (I am assuming here that it works kinda similar to how location permissions work. I have not delved into the code of the app myself.)

### Screenshots
Reset:
![Reset](https://user-images.githubusercontent.com/68731/93567513-0a7fab00-f98f-11ea-8be8-096cc1a6c596.jpg)

Blank screen:
![Blank screen](https://user-images.githubusercontent.com/68731/93567521-0ce20500-f98f-11ea-9368-2aaa4217cbb5.jpg)

There is a movie of the issue on Slack. (GitHub doesn't accept videos afaik.)

**Smartphone:**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.0
 - Version 1.0.7

### Governance
- [√] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [√] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [√] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md
 
* where "read" means "blindly accepted in good faith"  :-)

**Comment by roelspruit** [comment]
Hi. An updated version of the app that has a fix for this "blank screen" will be shipped soon. A lot of people mentioned this issue, thanks for being one of them :)

**Comment by sbarow** [comment]
@johankool this is updated in v1.0.10, you can update through the App Store.
