### ISSUE TITLE
On reinstall the app doesn't reactivate by itself

### ISSUE THREAD

**Issue by fvdm** [minvws/nl-covid19-notification-app-ios#52]
### Describe the bug, issue or concern

When you delete the app for whatever reason and later reinstall, the activation cannot complete. The 'Aanzetten' button does not do anything. You can only skip with 'Sla over' to continue.

### To Reproduce

1. Install the app from the App Store.
2. Complete the activation steps.
3. Close and delete the app.
4. Reinstall the app from the App Store.
5. Go through the activation steps.
6. When you arrive at the activation panel tap 'Aanzetten'

The buttons responds to touch, but nothing happens.

### Expected behavior
Upon reinstall the app completes the activation like a new install and adds the region to the iOS exposure settings.

Alternative: the app detects a previous install or odd settings and presents the correct manual steps.

### Screenshots

Video: https://fvdm.com/u/apps/coronamelder-reinstall-activation.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14.0.1
 - Browser: CoronaMelder app
 - Version 1.0.10

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
We encountered this issue too and had a really hard time reproducing it and finding the cause. Can you tell me if deleting the app, restarting your phone and then re-installing the app fixes it?

**Comment by fvdm** [comment]
@roelspruit I just tried, but it doesn't help. On reinstall after reboot it gets stuck on the same step.

**Comment by matthijsbreemans** [comment]
I have exactly the same issue on iOS 14, after i upgraded to iOS 14.0.1 the issue still exists.

Tried reinstalling and rebooting multiple times

**Comment by roelspruit** [comment]
Hi. We heard from another user that the instructions here might solve it. Can you try it out and let us know? https://mobile.twitter.com/_mbm_/status/1314914921252032512

**Comment by matthijsbreemans** [comment]
Awesome, that works! Should communicate this to the users.

Downside is that every app needs to request its iOS 14 permissions again, but that’s a minor issue considering the crisis we are in

**Comment by matthijsbreemans** [comment]
Solution is:

Instellingen -> algemeen -> stel opnieuw in -> herstel locatie en privacy

**Comment by roelspruit** [comment]
Thanks for checking. Hopefully we can think of a better solution soon.

**Comment by roelspruit** [comment]
For reference, our internal ticket number for this issue is 58916

**Comment by fvdm** [comment]
The suggested steps is a workaround at best. A system wide reset should never be required for normal use.

I hope you can find a user friendly solution.

**Comment by roelspruit** [comment]
I fully agree with you. We have asked Apple to look into this issue because unfortunately the cause seems to be in Apple's framework itself. We tried building a technical, non-invasive workaround that doesn't require manual steps from the user but haven't succeeded yet. We are now considering at least making a step-by-step instruction for the user in this scenario.

**Comment by roelspruit** [comment]
We finally got around to adding a screen to the onboarding of the app to notify users when this happens and which steps to take to resolve it. Thanks for your help with investigating this and coming to a (albeit not ideal) solution. The fix will be available in the upcoming version of the app.
