### ISSUE TITLE
Manual instructions are missing steps

### ISSUE THREAD

**Issue by fvdm** [minvws/nl-covid19-notification-app-ios#53]
### Describe the bug, issue or concern

I notice the manual instructions are missing steps on iOS 14 in case someone messed with the settings.

When the exposure tracking is enabled but somehow the region is removed, the app reports that it is not active and presents a button to go to the settings.

- After hitting the settings button the Settings app opens with the app's settings overview.
- There you have to go to 'Bloodstellingsmeldingen'
- enable 'Deel informatie over je blootstelling'
- and then tap 'Stel in als actieve regio'

The order is important. Without the toggle you cannot set the region.

### To Reproduce

1. Go to the Settings app.
2. Blootstellingsmeldingen
3. Actieve regio 'Ministerie...'
4. Ministerie van Volksgezondheid
5. Disable the toggle 'Deel informatie over je blootstelling'.
6. Go to the CoronaMelder app to see it is not active.
7. Hit 'App aanzetten'
8. You get the normal instructions that don't apply to this scenario.
9. Hit 'Open Instellingen'
10. You get the app settings instead of the global exposure settings.
11. See steps above to complete activation.

### Expected behavior
The app detects the settings are messed up and displays the appropriate steps to fix the activation, maybe even offer to automatically correct it, if possible.

Or the app displays instructions for both scenarios: a clean activation and fixing customized region settings.

### Screenshots
![image](https://user-images.githubusercontent.com/93784/95626381-775fff80-0a7a-11eb-8f37-a9fdd944d334.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14.0.1
 - Browser: CoronaMelder
 - Version: 1.0.10

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
Thank you for mentioning this issue. We noticed this also and have made an internal ticket to fix this (ticket nr 58899). We'll keep this issue updated too.

**Comment by roelspruit** [comment]
Hi. Again, thanks for your report. This issue has been addressed in the latest release (1.0.11)
