### ISSUE TITLE
Rename "signature" to "fingerprint" for the TLS pinning

### ISSUE THREAD

**Issue by xnyhps** [minvws/nl-covid19-notification-app-ios#57]
The iOS app has implemented TLS pinning, meaning it will not connect to servers unless the certificate matches a hash stored in the app.

This is implemented here:

https://github.com/minvws/nl-covid19-notification-app-ios/blob/6ec9eb3c2645494d47cee6e899ac3791f990cd58/Sources/ENCore/Common/Crypto/Certificates.swift#L32-L35

As can be seen here, this refers to the hash of the certificate as its "signature". This is very confusing, as a certificate has a signature field. That field is not what is used here, instead it uses what would normally (according to usual conventions in cryptography) be called a "hash" or "fingerprint". It takes the SHA-256 hash of the entire DER-encoded certificate.

If it had been using the signature, then this would be a vulnerability. A signature is only unforgeable if the key is fixed, if the attacker can still pick the public key then they can pick a key such that a message of their choosing matches the signature. See for example how this affected [Lets Encrypt](https://www.agwa.name/blog/post/duplicate_signature_key_selection_attack_in_lets_encrypt).

As I mentioned, this is not how it works, so this attack is not applicable. However, the confusing terminology is a risk. For example, It is possible that somebody in a later update completely rewrites the code, while making the incorrect assumption that it is using the signature field. Code that appears to be insecure could also lead to less trust in the app.

### Recommendation

I recommend renaming the "signature" used for TLS pinning to "fingerprint".

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
Hi. Thanks for your observation. We have made an internal ticket to fix this naming (ticket nr. 59179) And we will update you here once it has been changed.

**Comment by roelspruit** [comment]
We fixed this in the latest version of the app. Thanks for your report. I'm going to close this issue now.
