### ISSUE TITLE
[Enhancement request] Simple idea: a sound warning?

### ISSUE THREAD

**Issue by KoenKeunen** [minvws/nl-covid19-notification-app-ios#60]
### Describe the bug, issue or concern

Hi guys,
maybe a simple idea but I would really love it when my phone starts **beeping** when I'm closer than 1,5 from another device. And preferably, as annoying as possible ;-)

I'm not sure whether the technical limitations of bluetooth will allow for this, and i did not view any of your code, but if it's possible it should be rather easy to implement. This feature could have serious impact on society; with a beeper like this enabled, a lockdown in most public places would not be necessary anymore; it will keep people at at least 1,5 meters away from each other in supermarkets, restaurants, shops and other public places. The government could allow everyone who has the beeper enabled to keep doing social activities like work meetings, eating in restaurants, drinking a coffee at a pub, et cetera.

### Requirements
- Be able to set 10 'close friends' or family members
OR
- An easy on/off switch to turn the beeper off when arriving at home or a a close friend

Probably it won't work this way because of technical limitations, but I thought I'd at least propose it as a possibility. Keep up the good work!

**Comment by roelspruit** [comment]
Hi. Thanks for thinking along with us! At the moment there are indeed technical limitations to build such an alarm. Additionally such a feature would be outside the scope of the app that we are currently building, that is intended to only register prolonged contact and is intentionally not "real time".
