### ISSUE TITLE
Unclear exposure notification

### ISSUE THREAD

**Issue by DevSecNinja** [minvws/nl-covid19-notification-app-ios#61]
### Describe the bug, issue or concern

When the app notifies a person about a potential exposure, it will show an iOS Notification:

````
Title: Wekelijkse update
Description: Je apparaat heeft deze week 1 mogelijke blootstelling vastgesteld en heeft deze gedeeld met CoronaMelder."
````

English translation:
````
Title: Weekly update
Description: Your device identified 1 potential exposure this week, and shared it with CoronaMelder."
````

This notification is unclear and the CoronaMelder app itself will just show the green check. Based on my understanding, this notification tells the user that he/she was potentially exposed, but not long enough to be worried. Therefore the app will show a green check.

### Expected behavior
It seems that this notification comes from the COVID exposure integration of iOS, so it might not be possible to change it within this project. What would help is show more information to the user in the CoronaMelder app about the notification. Something like an orange check with a message below it saying: "Your device identified X potential exposure(s) this week. The exposure wasn't sufficient enough for you to quarantine, but be extra careful the coming days for COVID symptoms"

### Screenshots
![image](https://user-images.githubusercontent.com/14926452/97575256-c4d1eb80-19ec-11eb-8fa4-2c964e396b07.png)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS14
 - Browser: N/A
 - Version: N/A

### Governance
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
Hi,

Thank you for your detailed report. We are aware of the potential confusion that can occur between the CoronaMelder notifications and the notifications that iOS itself sends in these situations and this topic has priority for us too. 

I am going to close this issue for now but we will include your suggestion in our future discussions about this problem.
