### ISSUE TITLE
Links only work when Safari is set as default browser 

### ISSUE THREAD

**Issue by basst85** [minvws/nl-covid19-notification-app-ios#65]
### Describe the bug, issue or concern
Links, in for example "Colophon" or "Privacy Statement"), only work when Safari is set as default browser in iOS 14+
When I use Chrome, nothing happens when I click on the links.

A clear and concise description of what the bug, issue or concern is is.

Links, in for example "Colophon" or "Privacy Statement"), only work when Safari is set as default browser in iOS 14+
When I use Chrome, nothing happens when I click on the links.

### To Reproduce
1. Set Chrome as default browser in iOS  Settings (iOS 14+) 
2. Open the CoronaMelder app.
3. Click on "Questions about this app?".
3. Scroll down to 'Colophon' and click on it
4. Click on one of the links in the text.

### Expected behavior
Open the link in the default browser.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: IOS 14.2
 - Browser: Chrome
 - Version: Chrome 86.0.*

### Governance
- [*] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [*] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [*] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
Hi. thanks for the report. I copied this issue to our internal bug tracker (Ticket nr. 59245) and we will pick it up.

**Comment by roelspruit** [comment]
Just a small update. A fix for this is going into the upcoming app release. We expect this to ship next week.

**Comment by roelspruit** [comment]
We just released version 1.1 of the app that contains a fix for this issue. Again, thanks for your report. I'm going to close this issue now.
