### ISSUE TITLE
Best practice; remove deprecated code

### ISSUE THREAD

**Issue by johanneswk** [minvws/nl-covid19-notification-app-ios#66]
### Describe the bug, issue or concern

In _ENManager+ENManaging.swift_ is this function still being declared:
_func getExposureInfo(summary: ENExposureDetectionSummary, userExplanation: String, completionHandler: @escaping ENGetExposureInfoHandler) -> Progress_

According to Apple, this function is deprecated: [https://developer.apple.com/documentation/exposurenotification/enmanager/3586332-getexposureinfo](https://developer.apple.com/documentation/exposurenotification/enmanager/3586332-getexposureinfo)

### Expected behaviour
It is best practise to remove deprecated and unused code. 

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by noamschroeff** [comment]
Goed gespot! ik zie inderdaad dat het onder iets dat deprecated valt.

**Comment by Yassine2021** [comment]
Correct

**Comment by roelspruit** [comment]
Hi. Nice catch. It seems we don't even use this function at the moment anymore. I'll make a ticket to remove the code. (internal ticket #59721)

**Comment by roelspruit** [comment]
This has been resolved. Closing the ticket. Thanks again!
