### ISSUE TITLE
Sync CoronaCheck releases to GitHub before roll out. 

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-notification-app-ios#70]
Currently CoronaCheck version 2.1.1 and 2.1.3 are rolled out through the App Store, but not yet available in this GitHub repo. This undermines the open-source principals. Source code should be made first available on GitHub, before pushing to Apple and rolling out, so that it can be independently checked.

_Ping @roelspruit_

**Comment by roelspruit** [comment]
Hi. It seems you made this issue in the wrong repository. The CoronaCheck repository for the iOS app can be found here: https://github.com/minvws/nl-covid19-coronacheck-app-ios/issues. The apps are developed by separate teams so it is more effective to mention this issue over there.

**Comment by EwoutH** [comment]
You're right, thanks for the quick reply! I opened an issue over there. Al tags in this repo are synced, thanks!

I noticed however that the latest commit to the master branch was from June 1st, more than a month ago. There are no other (public) branches, and the commit https://github.com/minvws/nl-covid19-notification-app-ios/commit/a9c8f15a10287f43a74aadbf3c0874e88baa7b37 on which version [2.2.0](https://github.com/minvws/nl-covid19-notification-app-ios/releases/tag/2.2.0) has been tagged, isn't part of any branch.

Could the full Git history be synced before each release, and also periodically (for example once a week)? This makes it easier to review the changes between two releases.

**Comment by roelspruit** [comment]
Hey. no problem. You're not the first one to confuse the projects :)

Unfortunately we are currently in a situation where our master branch contains upcoming, unreleased work that may not become public yet (for various reasons). This is the reason the master branch is not in-sync with our in-house master branch at the moment. Obviously we try to avoid these kinds of situations as much as possible but in some cases it might not be possible. We do of course create tags/releases for the versions that are actually released in the mean time.

**Comment by EwoutH** [comment]
Would syncing a release/maintenance branch for those tags be an option?

**Comment by roelspruit** [comment]
Yeah that is a good suggestion thanks. I just published a release/2.2.0 branch that contains the work for the latest release. I'm going to close this issue now.
