### ISSUE TITLE
Quality Translations

### ISSUE THREAD

**Issue by tritter** [minvws/nl-covid19-notification-app-ios#73]
A german collegae using the dutch Corona app got a really weird translation.  "a**b**gesteckt" > "angesteckt" This means something like you may be "pegged". Mistakes like these are really bad for the main reputation of the app!

https://github.com/minvws/nl-covid19-notification-app-ios/blob/af6c825ef08617f5417f7a9dab219003102598a9/Sources/ENCore/Resources/de.lproj/Localizable.strings#L362

**Comment by 7hommay** [comment]
Thanks. Translations have been adjusted in OneSky
